[build]
  publish = "build"          # <--- CHANGE THIS LINE! It should be just "build"
  base = "frontend"          # This is correct and stays "frontend"
  command = "npm run build"  # This is correct

[build.environment]
  REACT_APP_BACKEND_URL = "https://nivas-backend.onrender.com/" # Your Backend API URL